Lesson4
crazyGibbon/react pull request #2
Opened 2021-08-07 12:59 UTC by crazyGibbon

2021-08-09 08:52 UTC, SokolAlexander commented on lesson4/src/components/HomePage/HomePage.js
> +const chatID = useParams();
useParams() возвращает объект типа { chatId: 'id' }

2021-08-09 08:53 UTC, SokolAlexander commented on lesson4/src/components/HomePage/HomePage.js
> +        [chatID]: [...chats[chatID], newMessage]
ну и соответственно тут chatID - не строка, а объект

2021-08-09 08:53 UTC, SokolAlexander requested changes
В целом ок, но вот с chatId надо поправить)

2021-11-21 01:22 UTC, closed without merging

2021-11-21 01:23 UTC, crazyGibbon commented
remove file